import os
import uuid
import json
from datetime import datetime, timezone
from flask import Flask, request, jsonify
from groq import Groq
from dotenv import load_dotenv

load_dotenv()

app = Flask(__name__)

client = Groq(api_key=os.getenv("GROQ_API_KEY"))

LOG_FILE = "audit_log.json"

def write_log(entry):
    logs = []
    if os.path.exists(LOG_FILE):
        with open(LOG_FILE, "r") as f:
            logs = json.load(f)
    logs.append(entry)
    with open(LOG_FILE, "w") as f:
        json.dump(logs, f, indent=2)

def get_log():
    if not os.path.exists(LOG_FILE):
        return []
    with open(LOG_FILE, "r") as f:
        return json.load(f)
    

def signal1_llm(text):
    prompt = f"""You are an AI content detection system. Analyze the following text and determine 
the likelihood that it was generated by an AI rather than written by a human.

Consider these factors:
- Unnatural smoothness or lack of awkward phrasing
- Overly balanced and structured paragraphs
- Generic confident tone with no hedging or uncertainty
- Technically correct but impersonal vocabulary

Respond with ONLY a JSON object in this exact format, nothing else:
{{"score": 0.0, "reasoning": "brief explanation"}}

Where score is between 0.0 (definitely human) and 1.0 (definitely AI).

Text to analyze:
{text}"""

    response = client.chat.completions.create(
        model="llama-3.3-70b-versatile",
        messages=[{"role": "user", "content": prompt}],
        temperature=0.1
    )

    raw = response.choices[0].message.content.strip()
    result = json.loads(raw)
    return round(float(result["score"]), 4)

@app.route("/submit", methods=["POST"])
def submit():
    data = request.get_json()
    if not data or "text" not in data or "creator_id" not in data:
        return jsonify({"error": "Missing text or creator_id"}), 400

    content_id = str(uuid.uuid4())
    text = data["text"]
    creator_id = data["creator_id"]

    # Placeholder values until signal is wired in
    llm_score = signal1_llm(text)
    confidence = round(llm_score * 0.65, 4)
    attribution = "likely_ai" if llm_score >= 0.65 else "uncertain" if llm_score >= 0.41 else "likely_human"
    label = "pending - full label logic in M5"

    entry = {
        "content_id": content_id,
        "creator_id": creator_id,
        "timestamp": datetime.now(timezone.utc).isoformat(),
        "attribution": attribution,
        "confidence": confidence,
        "llm_score": None,
        "status": "classified"
    }
    write_log(entry)

    return jsonify({
        "content_id": content_id,
        "attribution": attribution,
        "confidence": confidence,
        "label": label
    }), 200

@app.route("/log", methods=["GET"])
def log():
    return jsonify({"entries": get_log()}), 200

if __name__ == "__main__":
    app.run(debug=True)