import os
import uuid
import json
from datetime import datetime, timezone
from flask import Flask, request, jsonify
from groq import Groq
from dotenv import load_dotenv

load_dotenv()

app = Flask(__name__)

client = Groq(api_key=os.getenv("GROQ_API_KEY"))

LOG_FILE = "audit_log.json"

def write_log(entry):
    logs = []
    if os.path.exists(LOG_FILE):
        with open(LOG_FILE, "r") as f:
            logs = json.load(f)
    logs.append(entry)
    with open(LOG_FILE, "w") as f:
        json.dump(logs, f, indent=2)

def get_log():
    if not os.path.exists(LOG_FILE):
        return []
    with open(LOG_FILE, "r") as f:
        return json.load(f)
    

def signal1_llm(text):
    prompt = f"""You are an AI content detection system. Analyze the following text and determine 
the likelihood that it was generated by an AI rather than written by a human.

Consider these factors:
- Unnatural smoothness or lack of awkward phrasing
- Overly balanced and structured paragraphs
- Generic confident tone with no hedging or uncertainty
- Technically correct but impersonal vocabulary

Respond with ONLY a JSON object in this exact format, nothing else:
{{"score": 0.0, "reasoning": "brief explanation"}}

Where score is between 0.0 (definitely human) and 1.0 (definitely AI).

Text to analyze:
{text}"""

    response = client.chat.completions.create(
        model="llama-3.3-70b-versatile",
        messages=[{"role": "user", "content": prompt}],
        temperature=0.1
    )

    raw = response.choices[0].message.content.strip()
    result = json.loads(raw)
    return round(float(result["score"]), 4)

def signal2_stylometrics(text):
    import re
    
    # Split into sentences
    sentences = re.split(r'[.!?]+', text)
    sentences = [s.strip() for s in sentences if s.strip()]
    
    if len(sentences) < 2:
        return 0.5  # not enough text to analyze
    
    # Metric 1: sentence length variance
    # AI tends to write uniform sentence lengths, humans vary more
    sentence_lengths = [len(s.split()) for s in sentences]
    avg_len = sum(sentence_lengths) / len(sentence_lengths)
    variance = sum((l - avg_len) ** 2 for l in sentence_lengths) / len(sentence_lengths)
    # High variance = more human. Normalize: cap at 100, invert so high = AI
    normalized_variance = min(variance, 100) / 100
    sentence_score = 1.0 - normalized_variance  # high score = AI-like

    # Metric 2: type-token ratio (TTR)
    # AI reuses vocabulary more, giving lower TTR
    words = re.findall(r'\b\w+\b', text.lower())
    if len(words) == 0:
        return 0.5
    ttr = len(set(words)) / len(words)
    # Low TTR = AI-like. Invert so high score = AI
    ttr_score = 1.0 - ttr

    # Metric 3: punctuation density
    # Humans use more varied punctuation (dashes, ellipses, etc.)
    varied_punct = len(re.findall(r'[—\-–…]', text))
    total_chars = len(text)
    punct_density = varied_punct / total_chars if total_chars > 0 else 0
    # Low varied punctuation = AI-like. Normalize and invert
    normalized_punct = min(punct_density * 100, 1.0)
    punct_score = 1.0 - normalized_punct  # high score = AI-like

    # Average the three metrics
    final_score = round((sentence_score + ttr_score + punct_score) / 3, 4)
    return final_score

@app.route("/submit", methods=["POST"])
def submit():
    data = request.get_json()
    if not data or "text" not in data or "creator_id" not in data:
        return jsonify({"error": "Missing text or creator_id"}), 400

    content_id = str(uuid.uuid4())
    text = data["text"]
    creator_id = data["creator_id"]

    # Placeholder values until signal is wired in
    llm_score = signal1_llm(text)
    stylo_score = signal2_stylometrics(text)
    
    # Weighted blend per planning.md: LLM 65%, stylometrics 35%
    confidence = round((llm_score * 0.65) + (stylo_score * 0.35), 4)
    
    # Map to attribution per planning.md thresholds
    if confidence >= 0.65:
        attribution = "likely_ai"
    elif confidence >= 0.53:
        attribution = "uncertain_leaning_ai"
    elif confidence >= 0.41:
        attribution = "uncertain_leaning_human"
    else:
        attribution = "likely_human"
    
    label = "pending - full label logic in M5"

    entry = {
            "content_id": content_id,
            "creator_id": creator_id,
            "timestamp": datetime.now(timezone.utc).isoformat(),
            "attribution": attribution,
            "confidence": confidence,
            "llm_score": llm_score,
            "stylo_score": stylo_score,
            "status": "classified"
        }
    write_log(entry)

    return jsonify({
        "content_id": content_id,
        "attribution": attribution,
        "confidence": confidence,
        "label": label
    }), 200

@app.route("/log", methods=["GET"])
def log():
    return jsonify({"entries": get_log()}), 200

if __name__ == "__main__":
    app.run(debug=True)